// examples/svelte/src/ThemedCard.svelte
<script lang="ts">
  import type { PreviewDone, PreviewEmit } from "@nmnmcc/preview";
  import { getContext } from "svelte";
  import Card from "./Card.svelte";
  import { PreviewThemeKey, type CardTheme } from "./theme";

  let {
    done,
    emit,
  }: { readonly done: PreviewDone; readonly emit: PreviewEmit } = $props();

  const theme = getContext<CardTheme | undefined>(PreviewThemeKey);
  if (theme === undefined) {
    throw new Error("The preview theme context is missing.");
  }
</script>

<Card
  action="Change state"
  body="The Svelte mount context carries the selected matrix theme into this component."
  confirmedAction="State changed"
  eyebrow="Svelte context"
  heading="Typed props meet mount context."
  {done}
  {emit}
  {theme}
/>

// examples/vue/src/ThemedCard.vue
<script setup lang="ts">
import type { PreviewDone, PreviewEmit } from "@nmnmcc/preview";
import { inject } from "vue";
import Card from "./Card.vue";
import { PreviewThemeKey } from "./theme";

defineProps<{ readonly done: PreviewDone; readonly emit: PreviewEmit }>();

const theme = inject(PreviewThemeKey);
if (theme === undefined) {
  throw new Error("The preview theme provider is missing.");
}
</script>

<template>
  <Card
    action="Change state"
    body="Vue provide and inject carry the selected matrix theme into this component."
    confirmed-action="State changed"
    eyebrow="Vue provide/inject"
    heading="A provider for every variant."
    :done="done"
    :emit="emit"
    :theme="theme"
  />
</template>
